replicaCount: 1

image:
  repository: 551289997936.dkr.ecr.ap-south-1.amazonaws.com/ey-enterprise-repo
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
